server:
  port: 8080

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  security:
    csrf:
      enabled: false

  main:
    web-application-type: reactive

  data:
    redis:
      host: 127.0.0.1
      port: 6379

  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**, /oauth2/authorization/**, /api/auth/** # 이 경로로 요청이 들어오면 user-service로 전달

webflux:
  cors:
    mappings:
      /api/**:
        allowed-origins: "http://localhost:3000"
        allowed-methods: GET, POST, PUT, DELETE
        allowed-headers: "*"
        allow-credentials: true
        max-age: 3600

jwt:
  secretKey: gl1tat3lokz2752kj8zgzwetotb4mquvfFDJ2JOfeOIHJqOPIHJwraPOIHJ3
  access:
    expiration: 3600000 # 만료시간 30분 (1000 * 60 * 30)

  refresh:
    expiration: 1209600000 # 만료시간 2주 (60 * 60 * 24 * 14) / Duration