server:
  port: 0

spring:
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: taxi-consumer-group
      auto-offset-reset: earliest

  application:
    name: notification-service

jwt:
  secretKey: gl1tat3lokz2752kj8zgzwetotb4mquvfFDJ2JOfeOIHJqOPIHJwraPOIHJ3
  access:
    expiration: 3600000 # 만료시간 30분 (1000 * 60 * 30)

  refresh:
    expiration: 1209600000 # 만료시간 2주 (60 * 60 * 24 * 14) / Duration

logging:
  level:
    org.hibernate: info