server:
  port: 0

spring:
  config:
    import:
      - application-oauth.yml

  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://host.docker.internal:3306/taxi?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: redis
      port: 6379

eureka:
  instance:
    appname: USER-SERVICE
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secretKey: gl1tat3lokz2752kj8zgzwetotb4mquvfFDJ2JOfeOIHJqOPIHJwraPOIHJ3
  access:
    expiration: 3600000 # 만료시간 30분 (1000 * 60 * 30)

  refresh:
    expiration: 1209600000 # 만료시간 2주 (60 * 60 * 24 * 14) / Duration

logging:
  level:
    org.hibernate: info